---
# See https://github.com/aelsabbahy/goss/releases for release versions

- name: devops | paquetes generales
  apt:
    name:
      - jq
      - git
      - wget
      - curl
      - unzip
    state: present
  become: true
  tags:
    - devops
    - goss


- name: devops | goss | version actual instalada
  shell: |
     LANG=C /usr/local/bin/goss --version  | sed -n  -e "s/goss version[ ]*\([0-9\.]*\)/\1/p"
  register: reg_goss_version
  failed_when: false
  changed_when: false
  tags:
    - devops
    - goss


- name: devops | goss | busca el nombre de la version actual
  shell: |
      curl --silent https://api.github.com/repos/aelsabbahy/goss/releases/latest \
         | jq -r ".tag_name"

  register: reg_goss_url_version
  changed_when: false
  args:
    warn: false
  tags:
    - devops
    - goss

- set_fact:
    goss_version_instalada: "{{ reg_goss_version.rc == 0 and reg_goss_version.stdout or false }}"
    goss_url_version: "{{ reg_goss_url_version.stdout }}"
  tags:
    - devops
    - goss

- set_fact:
    goss_url_actual: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_url_version }}/goss-linux-amd64"
    dgoss_url_actual: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_url_version }}/dgoss"
  tags:
    - devops
    - goss

- debug:
    msg: "Goss, version instalada - {{ goss_version_instalada }}"
  tags:
    - devops
    - goss
- debug:
    msg: "Goss, url actual        - {{ goss_url_actual }}"
  tags:
    - devops
    - goss
- debug:
    msg: "Goss, url version       - {{ goss_url_version}}"
  tags:
    - devops
    - goss

- name: devops | goss | descarga paquete
  get_url:
    url: "{{ goss_url_actual }}"
    dest: /usr/local/bin/goss
    mode: 0755
    force: yes
    validate_certs: False
  become: true
  when: goss_version_instalada != goss_url_version
  tags:
    - devops
    - goss


- name: devops | dgoss | descarga paquete
  get_url:
    url: "{{ dgoss_url_actual }}"
    dest: /usr/local/bin/dgoss
    mode: 0755
    force: yes
    validate_certs: False
  become: true
  #when: goss_version_instalada != goss_url_version
  tags:
    - devops
    - goss


