roles:
  - name: geerlingguy.apache
    version: 3.2.0

  - name: geerlingguy.composer
    version: 1.9.0

  - name: geerlingguy.php
    version: 4.7.0

  - name: geerlingguy.php-versions
    version: 5.0.0

  - name: geerlingguy.mysql
    version: 3.3.2

  - name: geerlingguy.php-mysql 
    version: 2.1.0

  - name: geerlingguy.phpmyadmin
    version: 1.3.3
